version: '3'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6370
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf
volumes:
  postgres-data:
  redis-data:
